name: auto-assign
on:
  pull_request:

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: johnmanjiro13/auto-assign@950433c95013bb786eb256bafdb66f934f624601
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
