name: auto-assign
on:
  pull_request:

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: johnmanjiro13/auto-assign@c8db73207f75d10df217d7e3e91f3b0743b17bdc
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
