name: share variables
on:
  push:
    branches:
      - main

jobs:
  share:
    runs-on: ubuntu-latest
    steps:
      - run: echo "msg=$(echo 'fuga')" >> $GITHUB_ENV
      - run: echo $MSG
        env:
          MSG: $msg
