name: share variables
on:
  push:
    branches:
      - main

jobs:
  share:
    runs-on: ubuntu-latest
    steps:
      - run: echo "SLACK_MESSAGE=$(echo 'fuga')" >> $GITHUB_ENV
      - run: echo $SLACK_MESSAGE
